server:
  port: 9000

logging:
  level:
    'com.conceptile.quiz': INFO

spring:
  application:
    name: quiz
  profiles:
    active: default
  data:
    mongodb:
      uri: mongodb+srv://conceptilequizv1:NTeXRhkerjAXU4F2@cluster0.eingv.mongodb.net/conceptile?retryWrites=true&w=majority&appName=Cluster0
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

question:
  count: 10